# 实验名称
experiment: "SAN"

# 随机种子
seed: 20230518

# 训练参数
epoches: 350
batch_size: 5
workers: 0
optimizer: Momentum
lr: 0.05
lr_decay: cosine
step_ratio: 20
step_decay: 2
eps: 1e-6
weight_decay: 1e-4
beta: 0.9
image_resize: True
image_width: 1600
image_height: 320
image_channel: 1
dropout: True
dropout_ratio: 0.5
relu: True
gradient: 100
gradient_clip: True
use_label_mask: False

# 训练数据
train_image_path: 'data/CROHME/train_image.pkl'
train_label_path: 'data/CROHME/train_label.pkl'
eval_image_path: 'data/CROHME/test_image.pkl'
eval_label_path: 'data/CROHME/test_label.pkl'

word_path: 'data/word.txt'

# 选择encoder
encoder:
  net: DenseNet
  input_channels: 1
  out_channels: 684

resnet:
  conv1_stride: 1

densenet:
  ratio: 16
  growthRate: 24
  reduction: 0.5
  bottleneck: True
  use_dropout: True

# 使用的rnn cell
decoder:
  net: SAN_decoder
  cell: 'GRU'
  input_size: 256
  hidden_size: 256

# attention 参数
attention:
  attention_dim: 512

# hybrid tree
hybrid_tree:
  threshold: 0.5

# 训练权重存放路径
optimizer_save: False
checkpoint_dir: 'checkpoints'
finetune: False
checkpoint: ""
#checkpoint: "checkpoints/SAN_2023-04-24-14-27_Encoder-DenseNet_Decoder-SAN_decoder_max_size-320-1600/SAN_2023-04-24-14-27_Encoder-DenseNet_Decoder-SAN_decoder_max_size-320-1600_WordRate-0.7371_structRate-0.9706_ExpRate-0.3398_52.pth"

# tensorboard路径
log_dir: 'logs'
